version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:4.0.2
    steps:
      - checkout
      - run:
          command: |
            R -e 'devtools::check()'
      - store_artifacts:
          path: man/
          destination: man

